fit/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path,include,re_path
from django.contrib.auth.views import LogoutView
from .views import fit_curve

app_name = 'fit'
urlpatterns = [
	path('',fit_curve, name='fiting'),

]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

timeseries/urls.py
from django.contrib import admin
from django.urls import path,include
from fit.views import home

urlpatterns = [
	path('',home,name='home'),
    path('admin/', admin.site.urls),
    path('fit/',include('fit.urls')),
]

fit/models.py
from django.db import models

# Create your models here.

fit/views.py
from django.shortcuts import render
from django.contrib import messages
import math

def home(request):
    return render(request, 'home.html',)

def fit_curve(request):
	if request.method == "POST":
		years = request.POST.get('years').split(',')
		values = request.POST.get('values').split(',')
		n = len(years)
		middle = int(request.POST.get('middle'))	
		t = [int(yr)-int(middle) for yr in years]	
		t2 = [v**2 for v in t]				
		X_t = [float(v) for v in values]
		fittype = request.POST.get('fittype')
		if len(years) != len(X_t):
			messages.add_message(request, messages.WARNING, 
				"Years and Values length don't match"
			)
			return render(request, 'straight.html')
		else: 
			if fittype == 'straight':
				t_X_t = []
				for i in range(len(t)):
					t_X_t.append(int(X_t[i])*t[i])	
				b_hat = round((n*sum(t_X_t) - sum(t)*sum(X_t))/(n*sum(t2)-sum(t)**2),4)
				a_hat = round((sum(X_t) - b_hat*sum(t))/n,4)
				x_bar_t = [round(a_hat+(v*b_hat),2) for v in t]
				variation = []
				for i in range(n):
					variation.append(round(X_t[i]-x_bar_t[i],2))
				context = {
					'fittype':fittype,'years':years,
					't':t,'xt':X_t,'t2':t2,'sum_X_t':round(sum(X_t),2),
					'middle':middle,'txt':t_X_t,'sum_t':round(sum(t),2),'sum_t2':round(sum(t2),2),
					'b_hat':b_hat,"a_hat":a_hat,'x_bar_t':x_bar_t,
					'variation':variation,'sum_t_X_t':round(sum(t_X_t),2)
				}
				return render(request, 'straight.html',context)
			elif fittype == 'exponential':
				V = [round(math.log(v),4) for v in X_t]
				t_V = []
				for i in range(n):
					t_V.append(round(t[i]*V[i],3))
				B_hat = round((n*sum(t_V) - sum(t)*sum(V))/(n*sum(t2)-sum(t)**2),4)
				A_hat = round((sum(V) - B_hat*sum(t))/n,4)

				b_hat =round(math.exp(B_hat),4)
				a_hat = round(math.exp(A_hat),4)
				y_hat = [round(a_hat*b_hat**v,4) for v in t]
				variation = []
				for i in range(n):
					variation.append(round(X_t[i]-y_hat[i],4))
				context = {
					'fittype':fittype,'years':years,
					't':t,'Y':X_t,'t2':t2,"sum_t":round(sum(t),4),'sum_t2':round(sum(t2),4),
					'middle':middle,'V':V, 'sum_V':round(sum(V),4),
					'B_hat':B_hat,"A_hat":A_hat,
					'b_hat':b_hat,"a_hat":a_hat,
					't_V':t_V,"sum_t_V":round(sum(t_V),4),
					'y_hat':y_hat,'variation':variation,
				}				
				return render(request, 'straight.html',context)
			elif fittype == '':
				pass
			elif fittype == '':
				pass								
	else:
		return render(request, 'straight.html')

fit/templates/base.html
{%load static %}
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <title>Time Series</title>
  <meta content="width=device-width, initial-scale=1.0" name="viewport">
  <meta content="" name="keywords">
  <meta content="" name="description">


  <!-- Google Fonts -->
  <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,700,700i|Roboto:100,300,400,500,700|Philosopher:400,400i,700,700i" rel="stylesheet">

  <!-- Bootstrap css -->
  <!-- <link rel="stylesheet" href="css/bootstrap.css"> -->
  <link href="{% static 'lib/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">
<style type="text/css">
  .sub{
    vertical-align: sub;
  }
  .super{
    vertical-align: super;
  }
  .bold{
    font-weight: bold;
  }
</style>
</head>

<body>
  {%include './header.html' %}

  {% block content %}
    {% if messages %}
      {% for message in messages %}       
        <div class="alert alert-{{message.tags}} alert-dismissible fade show" role="alert">
          {{message}}
          <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>              
      {% endfor %}
    {% endif %}

  {% endblock %}

  <a href="#" class="back-to-top"><i class="fa fa-chevron-up"></i></a>

  <!-- JavaScript Libraries -->
  <script src="{% static 'lib/jquery/jquery.min.js' %}"></script>
  <script src="{% static 'lib/jquery/jquery-migrate.min.js' %}"></script>
  <script src="{% static 'lib/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
  <script src="{% static 'lib/superfish/hoverIntent.js' %}"></script>
  <script src="{% static 'lib/superfish/superfish.min.js' %}"></script>
  <script src="{% static 'lib/easing/easing.min.js' %}"></script>

  <!-- Template Main Javascript File -->
  <script src="{% static 'js/main.js' %}"></script>

</body>
</html>

fit/templates/header.html
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="#">TimeSeries</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <a class="nav-link" href="#">Home <span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'fit:fiting' %}">Fitting</a>
      </li>

      <li class="nav-item">
        <a class="nav-link disabled" href="#" tabindex="-1" aria-disabled="true">Disabled</a>
      </li>
    </ul>
    <form class="form-inline my-2 my-lg-0">
      <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
      <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
    </form>
  </div>
</nav>

fit/templates/home.html
{% extends "base.html" %}
{% load static %}
{% block title %}Home{% endblock%}
{% block extrahead%}
<style type="text/css">
</style>
{% endblock%}

{% block content %}
<div class="container">

</div>

{% endblock %}

fit/templates/straight.html
{% extends "base.html" %}
{% load static %}
{% block title %}Home{% endblock%}
{% block extrahead%}
<style type="text/css">
</style>
{% endblock%}
<h1>Curve Fitting lines with OLS </h1>
{% block content %}
	{{ block.super }}
<div class="container">
	<div class="row">
		<div class="col">
			<div class="col">
				<form method="POST">
					{% csrf_token %}

				  <div class="form-group">
				    <label for="years">Years</label>
				    <input required="true" type="text" class="form-control" id="years" name="years" aria-describedby="emailHelp" placeholder="Separated by comma">
				  </div>
				  <div class="form-group">
				    <label for="values">Values </label>
				    <input required="true" type="text" class="form-control" id="values" name="values" placeholder="separated by comma">
				  </div>
				  <div class="form-group">
				    <label for="middle">Middle Year</label>
				    <input required="true" type="text" class="form-control" id="middle" name="middle">
				  </div>			  
				  <div class="form-group">
				    <label for="fittype">Fitting type</label>
				    <select class="form-control" id="fittype" name="fittype">
				      <option>straight</option>
				      <option>exponential</option>
				      <option>exponential(modified)</option>
				      <option>Gompertz</option>
				      <option>Other</option>
				    </select>
				  </div>				  

				  <button type="submit" class="btn btn-primary">Submit</button>
				</form>
					
			</div>			
		</div>
	</div>	
	{%if fittype == 'straight' %}
		<div class="row ">
			<div class="col">
				<h3>{{fittype}} curve fitting with ols</h3>
				<table class="table table-responsive table-striped table-sm">
				    <tr>
				      <td class="bold">Years</td>
						{%for v in years %}
							<td>{{v}}</td>
						{%endfor%}
				    </tr>
				    <tr>
				      <td class="bold">X<span class="sub">t</span></td>    	
						{%for v in xt %}
							<td>{{v}}</td>
						{%endfor%}
						<td>{{sum_X_t}}</td>
				    </tr>
				    <tr>
				      <td class="bold">t=Year-{{middle}}</td>
						{%for v in t %}
							<td>{{v}}</td>
						{%endfor%}			
						<td>{{sum_t}}</td>      
				    </tr>
				    <tr>
				    	<td class="bold">t<span class="super">2</span></td>
						{%for v in t2 %}
							<td>{{v}}</td>
						{%endfor%}
						<td>{{sum_t2}}</td>
				    </tr>
				    <tr>
				    	<td class="bold">t.X<span class="sub">t</span></td>
						{%for v in txt %}
							<td>{{v}}</td>
						{%endfor%}
						<td>{{sum_t_X_t}}</td>
				    </tr>			    
				</table>			
			</div>
			<div class="col">
				<p> X&#770; <sub>t</sub> = a&#770; + b&#770; <sub>t</sub></p>
				<p>
					b&#770; = (n&#x2211; t*X<sub>t</sub> - &#x2211;t &#x2211;X<sub>t</sub>)/
					(n&#x2211;t<sup>2</sup>) - (&#x2211;t)<sup>2</sup>)
				</p>
				<p>
					b&#770; = {{b_hat}} <- yearly increment/decrement <br>
					b&#770;/12 <- monthly increment/decrement
				</p>
				<p>
					a&#770; = {{a_hat}}
				</p>
				<p>
					X&#770;<sub>t</sub> = a&#770; + b&#770;<sub>t</sub> <br>
					So: X&#770;<sub>t</sub> = {{a_hat}} + {{b_hat}} * t   <- the fitted trend line <br>
				</p>
				<table class="table table table-responsive table-striped table-sm">
				    <tr>
				      <td class="bold">X<span class="sub">t</span></td>    	
						{%for v in xt %}
							<td>{{v}}</td>
						{%endfor%}
				    </tr>
				    <tr>
				      <td class="bold">X&#770;<sub>t</sub></td>
						{%for v in x_bar_t %}
							<td>{{v}}</td>
						{%endfor%}			      
				    </tr>
				    <tr>
				    	<td class="bold">X<span class="sub">t - X&#770;<sub>t</sub></span></td>
						{%for v in variation %}
							<td>{{v}}</td>
						{%endfor%}
				    </tr>
			    
				</table>			

			</div>
		</div>	
	{%elif fittype == 'exponential' %}
		<div class="row">
			<div class="col">
				<p>
					Y = ab<sup>x</sup> + e<sub>t</sub>
				</p>
				<table class="table table-responsive table-striped table-sm">
				    <tr>
				      <td class="bold">Years(X)</td>
						{%for v in years %}
							<td>{{v}}</td>
						{%endfor%}
				    </tr>
				    <tr>
				      <td class="bold">Y(Values)</td>    	
						{%for v in Y %}
							<td>{{v}}</td>
						{%endfor%}
				    </tr>
				    <tr>
				      <td class="bold">t=X-{{middle}}</td>
						{%for v in t %}
							<td>{{v}}</td>
						{%endfor%}	
						<td>{{sum_t}}</td>		      
				    </tr>
				    <tr>
				    	<td class="bold">V = ln Y</td>
						{%for v in V %}
							<td>{{v}}</td>
						{%endfor%}
						<td>{{sum_V}}</td>
				    </tr>
				    <tr>
				    	<td class="bold">t<sup>2</sup></td>
						{%for v in t2 %}
							<td>{{v}}</td>
						{%endfor%}
						<td>{{sum_t2}}</td>
				    </tr>				    
				    <tr>
				    	<td class="bold">t.V</td>
						{%for v in t_V %}
							<td>{{v}}</td>
						{%endfor%}
						<td>{{sum_t_V}}</td>
				    </tr>			    
				</table>
			</div>		
			<div class="col">
				<p>
					B&#770; = {{B_hat}}<br>
					A&#770; = {{A_hat}}<br>	

					b&#770; = {{b_hat}}<br>
					a&#770; = {{a_hat}}<br>							
				</p>			
				<p>
					The fitted exponential curve is: Y&#770; = a&#770;*b&#770;<sup>t</sup> <br>
					=> {{a_hat}}({{b_hat}})<sup>t</sup>
				</p>		
				<table class="table table table-responsive table-striped table-sm">
				    <tr>
				      <td class="bold">Y</td>    	
						{%for v in Y %}
							<td>{{v}}</td>
						{%endfor%}
				    </tr>
				    <tr>
				      <td class="bold">Y&#770;</td>
						{%for v in y_hat %}
							<td>{{v}}</td>
						{%endfor%}			      
				    </tr>
				    <tr>
				    	<td class="bold">X<span class="sub">t - X&#770;<sub>t</sub></span></td>
						{%for v in variation %}
							<td>{{v}}</td>
						{%endfor%}
				    </tr>
			    
				</table>							
			</div>	
		</div>
	{%endif%}
	
</div>
{% endblock %}